import 'package:flutter_application_1/features/anime/domain/entities/user_anime_entity.dart';

class UserAnimeModel extends UserAnimeEntity {
  const UserAnimeModel({
    required super.id,
    required super.userId,
    required super.animeId,
    required super.status,
    required super.watchedEpisodes,
    required super.userRating,
    required super.notes,
    required super.createdAt,
    required super.updatedAt,
  });

  // Factory constructor from JSON
  factory UserAnimeModel.fromJson(Map<String, dynamic> json) {
    return UserAnimeModel(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      animeId: json['anime_id'] as String,
      status: json['status'] as String,
      watchedEpisodes: json['watched_episodes'] as int? ?? 0,
      userRating: json['user_rating'] != null 
          ? (json['user_rating'] as num).toDouble() 
          : null,
      notes: json['notes'] as String? ?? '',
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: json['updated_at'] != null ? DateTime.parse(json['updated_at'] as String) : null,
    );
  }

  // Convert to JSON for Supabase (snake_case)
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'anime_id': animeId,
      'status': status,
      'watched_episodes': watchedEpisodes,
      'user_rating': userRating,
      'notes': notes,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }

  // Factory constructor for creating new user anime entry
  factory UserAnimeModel.create({
    required String userId,
    required String animeId,
    required String status,
    int watchedEpisodes = 0,
    double? userRating,
    String? notes,
  }) {
    final now = DateTime.now();
    return UserAnimeModel(
      id: '', // Will be generated by database
      userId: userId,
      animeId: animeId,
      status: status,
      watchedEpisodes: watchedEpisodes,
      userRating: userRating,
      notes: notes ?? '',
      createdAt: now,
      updatedAt: now,
    );
  }

  // Copy with method for updates
  UserAnimeModel copyWith({
    String? id,
    String? userId,
    String? animeId,
    String? status,
    int? watchedEpisodes,
    double? userRating,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return UserAnimeModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      animeId: animeId ?? this.animeId,
      status: status ?? this.status,
      watchedEpisodes: watchedEpisodes ?? this.watchedEpisodes,
      userRating: userRating ?? this.userRating,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}